name: 'Confluence site builder'
description:
  'Builds site.yaml which can be used to deploy pages using bsorrentino/maven-confluence-plugin'
author: 'Simonas Bunevicius'
inputs:
  localDirectory:
    required: true
    default: 'confluence'
    description: 'Directory that contains confluence pages'
  workingDirectory:
    required: false
    description:
      'A directory for storing site.yaml file. You can also think of it as outputDirecotry'
  parentPageTitle:
    required: true
    description: 'Parent page title'
  homePageTitle:
    required: true
    description: 'Home page title'
  spaceKey:
    required: true
    description: 'Space name'
runs:
  using: 'node16'
  main: 'dist/index.js'
  post: dist/index.js
